# Generated by Django 4.0.6 on 2022-12-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
